[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[Solana]]

ChainID = 'devnet'
Enabled = true

[[Solana.Nodes]]
Name = 'Solana_Mainnet_test_88'
URL = '<SOLANA_DEVNET_RPC>'